<?php

function travelcase_views_api() {
  return array('api' => 3.0);
}

function travelcase_views_default_views() {
  civicrm_initialize();
  $files = file_scan_directory(drupal_get_path('module', 'travelcase'). '/views', '/.inc/');
  $views = array();
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

function _travelcase_get_fa_sponsor_display_name($case_id) {
  $contact_id = _travelcase_get_fa_sponsor_contact_id($case_id);
  if (!$contact_id) {
    return false;
  }
  
  $contact_params['id'] = $contact_id;
  $contact_params['return'] = 'display_name';
  return civicrm_api3('Contact', 'getvalue', $contact_params);
}

function _travelcase_get_fa_sponsor_code($case_id) {
  $contact_id = _travelcase_get_fa_sponsor_contact_id($case_id);
  if (!$contact_id) {
    return false;
  }
  
  $sponsor_code_group = civicrm_api3('CustomGroup', 'getsingle', array('name' => 'Donor_details_FA'));
  $sponsor_code_field = civicrm_api3('CustomField', 'getvalue', array('name' => 'Donor_code', 'return' => 'id', 'custom_group_id' => $sponsor_code_group['id']));
  
  $contact_params['id'] = $contact_id;
  $contact_params['return'] = 'custom_'.$sponsor_code_field;
  return civicrm_api3('Contact', 'getvalue', $contact_params);
}

function _travelcase_get_fa_sponsor_contact_id($case_id) {
  static $contact_ids = array();
  
  if (!isset($contact_ids[$case_id])) {
    $fa_donor_params = array(
      'entity_id' => $case_id,
      'entity' => 'Case',
      'is_fa_donor' => 1
    );
    $fa_donation = CRM_Threepeas_BAO_PumDonorLink::getValues($fa_donor_params);
    $fa_donation = reset($fa_donation);
    $donor_contact_id = false;
    if ($fa_donation['donation_entity'] == 'Contribution') {
      $donor_contact_id = civicrm_api3('Contribution', 'getvalue', array(
        'return' => 'contact_id',
        'id' => $fa_donation['donation_entity_id'],
      ));
    }
    $contact_ids[$case_id] = $donor_contact_id;
  }
  
  return $contact_ids[$case_id];
}

function travelcase_get_role_ids($roles) {
  $rids = array();
  $available_roles = user_roles();
  foreach($roles as $role) {
    $rid = array_search($role, $available_roles);
    if ($rid !== false) {
      $rids[$rid] = $rid;
    }
  }
  
  return $rids;
}